function [ID,aesthetic_score]=load_ids_score(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/ferradans/Desktop/challenge/Regaind/control-Sira/challenge_output_data_training_file_predict_the_aesthetic_score_of_a_photograph.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/04 11:13:13

%% Initialize variables.
%filename = '/Users/ferradans/Desktop/challenge/Regaind/control-Sira/challenge_output_data_training_file_predict_the_aesthetic_score_of_a_photograph.csv';
delimiter = ';';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
ID = dataArray{:, 1};
aesthetic_score = dataArray{:, 2};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
end 